ir_version: 11
domain: "eu.neverblink.rdf"
model_version: 1
doc_string: "RDF tensor scaling function"
graph {
  node {
    input: "input1"
    output: "cast_input"
    op_type: "Cast"
    attribute {
      name: "to"
      i: 11
      type: INT
    }
  }
  node {
    input: "cast_input"
    input: "factor"
    output: "output1"
    op_type: "Mul"
  }
  initializer {
    data_type: 11
    name: "factor"
    double_data: <factor_value>
  }
  input {
    name: "input1"
    type {
      tensor_type {
        elem_type: <input_type>
      }
    }
  }
  output {
    name: "output1"
    type {
      tensor_type {
        elem_type: 11
      }
    }
  }
}
opset_import {
  version: 23
}
