ir_version: 11
domain: "eu.neverblink.rdf"
model_version: 1
doc_string: "RDF tensor none function"
graph {
  node {
    input: "input1"
    output: "cast_input"
    op_type: "Cast"
    attribute {
      name: "to"
      i: 9
      type: INT
    }
  }
  node {
    input: "cast_input"
    output: "reduced_input"
    op_type: "ReduceMax"
    attribute {
      name: "keepdims"
      i: 1
      type: INT
    }
  }
  node {
    input: "reduced_input"
    output: "output1"
    op_type: "Not"
  }
  input {
    name: "input1"
    type {
      tensor_type {
        elem_type: <input_type>
      }
    }
  }
  output {
    name: "output1"
    type {
      tensor_type {
        elem_type: 9
      }
    }
  }
}
opset_import {
  version: 23
}
