ir_version: 11
domain: "eu.neverblink.rdf"
model_version: 1
doc_string: "RDF tensor sorting function"
graph {
  node {
    input: "input1"
    input: "k_tensor"
    output: "output1"
    output: "indices"
    op_type: "TopK"
    attribute {
      name: "axis"
      i: <axis_value>
      type: INT
    }
    attribute {
      name: "largest"
      i: <largest_value>
      type: INT
    }
    attribute {
      name: "sorted"
      i: 1
      type: INT
    }
  }
  initializer {
    dims: 1
    data_type: 7
    int64_data: <axis_size_value>
    name: "k_tensor"
  }
  input {
    name: "input1"
    type {
      tensor_type {
        elem_type: <input_type>
      }
    }
  }
  output {
    name: "output1"
    type {
      tensor_type {
        elem_type: <input_type>
      }
    }
  }
}
opset_import {
  version: 23
}
