ir_version: 11
domain: "eu.neverblink.rdf"
model_version: 1
doc_string: "RDF tensor not function"
graph {
  node {
    input: "input1"
    output: "output1"
    op_type: "Not"
  }
  input {
    name: "input1"
    type {
      tensor_type {
        elem_type: <input_type>
      }
    }
  }
  output {
    name: "output1"
    type {
      tensor_type {
        elem_type: <input_type>
      }
    }
  }
}
opset_import {
  version: 23
}
