ir_version: 11
domain: "eu.neverblink.rdf"
model_version: 1
doc_string: "RDF tensor vstack function for 1D tensors"
graph {
  node {
    input: "input1"
    output: "cast_input1"
    op_type: "Cast"
    attribute {
      name: "to"
      i: <resolved_type>
      type: INT
    }
  }
  node {
    input: "input2"
    output: "cast_input2"
    op_type: "Cast"
    attribute {
      name: "to"
      i: <resolved_type>
      type: INT
    }
  }
  node {
    input: "input3"
    output: "cast_input3"
    op_type: "Cast"
    attribute {
      name: "to"
      i: <resolved_type>
      type: INT
    }
  }
  ...
  node {
    input: "inputN"
    output: "cast_inputN"
    op_type: "Cast"
    attribute {
      name: "to"
      i: <resolved_type>
      type: INT
    }
  }
  node {
    input: "cast_input1"
    input: "unsqueeze_axes"
    output: "unsqueezed_input1"
    op_type: "Unsqueeze"
  }
  node {
    input: "cast_input2"
    input: "unsqueeze_axes"
    output: "unsqueezed_input2"
    op_type: "Unsqueeze"
  }
  node {
    input: "cast_input3"
    input: "unsqueeze_axes"
    output: "unsqueezed_input3"
    op_type: "Unsqueeze"
  }
  ...
  node {
    input: "cast_inputN"
    input: "unsqueeze_axes"
    output: "unsqueezed_inputN"
    op_type: "Unsqueeze"
  }
  node {
    input: "unsqueezed_input1"
    input: "unsqueezed_input2"
    input: "unsqueezed_input3"
    ...
    input: "unsqueezed_inputN"
    output: "output1"
    op_type: "Concat"
    attribute {
      name: "axis"
      i: 0
      type: INT
    }
  }
  initializer {
    dims: 1
    data_type: 7
    int64_data: 0
    name: "unsqueeze_axes"
  }
  input {
    name: "input1"
    type {
      tensor_type {
        elem_type: <input1_type>
      }
    }
  }
  input {
    name: "input2"
    type {
      tensor_type {
        elem_type: <input2_type>
      }
    }
  }
  input {
    name: "input3"
    type {
      tensor_type {
        elem_type: <input3_type>
      }
    }
  }
  ...
  input {
    name: "inputN"
    type {
      tensor_type {
        elem_type: <inputN_type>
      }
    }
  }
  output {
    name: "output1"
    type {
      tensor_type {
        elem_type: <resolved_type>
      }
    }
  }
}
opset_import {
  version: 23
}
