ir_version: 11
domain: "eu.neverblink.rdf"
model_version: 1
doc_string: "RDF tensor sum function for full reduction and int16 data type"
graph {
  node {
    input: "input1"
    output: "cast_input"
    op_type: "Cast"
    attribute {
      name: "to"
      i: 6
      type: INT
    }
  }
  node {
    input: "cast_input"
    output: "reduction_output"
    op_type: "ReduceSum"
    attribute {
      name: "keepdims"
      i: 1
      type: INT
    }
  }
  node {
    input: "reduction_output"
    output: "output1"
    op_type: "Cast"
    attribute {
      name: "to"
      i: 5
      type: INT
    }
  }
  input {
    name: "input1"
    type {
      tensor_type {
        elem_type: 5
      }
    }
  }
  output {
    name: "output1"
    type {
      tensor_type {
        elem_type: 5
      }
    }
  }
}
opset_import {
  version: 23
}
