ir_version: 11
domain: "eu.neverblink.rdf"
model_version: 1
doc_string: "RDF tensor STD aggregation function reduction step"
graph {
  node {
    input: "input3"
    output: "cast_new"
    op_type: "Cast"
    attribute {
      name: "to"
      i: 11
      type: INT
    }
  }
  node {
    input: "cast_new"
    input: "cast_new"
    output: "newSq"
    op_type: "Mul"
  }
  node {
    input: "newSq"
    input: "input1"
    output: "output1"
    op_type: "Add"
  }
  node {
    input: "cast_new"
    input: "input2"
    output: "output2"
    op_type: "Add"
  }
  input {
    name: "input1"
    type {
      tensor_type {
        elem_type: 11
      }
    }
  }
  input {
    name: "input2"
    type {
      tensor_type {
        elem_type: 11
      }
    }
  }
  input {
    name: "input3"
    type {
      tensor_type {
        elem_type: <input_type>
      }
    }
  }
  output {
    name: "output1"
    type {
      tensor_type {
        elem_type: 11
      }
    }
  }
  output {
    name: "output2"
    type {
      tensor_type {
        elem_type: 11
      }
    }
  }
}
opset_import {
  version: 23
}
